export const FILTER_OPTIONS = {
  minExperience: Array.from({ length: 10 }, (_, i) => (i + 1).toString()),
  locations: ["mumbai", "delhi ncr", "chennai"],
  remoteOnSite: ["Remote", "Hybrid", "In-office"],
  techStack: [
    "python",
    "java",
    "golang",
    "ruby/rails",
    "C++",
    "Kotlin",
    "Django",
    "C#",
    "GraphQL",
    "Flask",
    "Typescript",
    "AWS",
    "Javascript",
    "Rust",
    "NodeJS",
    "React",
  ],
  roles: [
    "ENGINEERING: Backend",
    "Frontend",
    "Fullstack",
    "IOS",
    "Flutter",
    "React Native",
    "Android",
    "Frontend",
    "DESIGN: Designer",
    "Design Manager",
    "Graphic Designer",
    "Product Designer",
    "PRODUCT: Product Manager",
  ],
  minBasePay: ["OL", "10L", "20L", "30L", "40L", "50L", "60L", "70L"],
};
