export const FILTER_OPTIONS = {
  minExperience: Array.from({ length: 10 }, (_, i) => (i + 1).toString()),
  locations: ["mumbai", "delhi ncr", "chennai"],
  remoteOnSite: ["remote", "hybrid", "in-office"],
  techStack: [
    "python",
    "java",
    "golang",
    "ruby/rails",
    "c++",
    "kotlin",
    "django",
    "c#",
    "graphql",
    "flask",
    "typescript",
    "aws",
    "javascript",
    "rust",
    "nodeJS",
    "react",
  ],
  roles: [
    {
      title: "Engineering",
      list: [
        "backend",
        "frontend",
        "fullstack",
        "ios",
        "flutter",
        "react native",
        "android",
      ],
    },
    {
      title: "Design",
      list: [
        "designer",
        "design manager",
        "graphic designer",
        "product designer",
      ],
    },
    {
      title: "Product",
      list: ["product manager"],
    },
  ],
  minBasePay: [0, 5, 10, 20, 30, 40, 50, 60, 70],
};
