export const FILTER_OPTIONS = {
  minExperience: Array.from({ length: 10 }, (_, i) => (i + 1).toString()),
  locations: ["mumbai", "delhi ncr", "chennai"],
  remoteOnSite: ["remote", "hybrid", "in-office"],
  techStack: [
    "python",
    "java",
    "golang",
    "ruby/rails",
    "c++",
    "kotlin",
    "django",
    "c#",
    "graphql",
    "flask",
    "typescript",
    "aws",
    "javascript",
    "rust",
    "nodeJS",
    "react",
  ],
  roles: [
    "Backend",
    "Frontend",
    "Fullstack",
    "IOS",
    "Flutter",
    "React Native",
    "Android",
    "Frontend",
    "Designer",
    "Design Manager",
    "Graphic Designer",
    "Product Designer",
    "Product Manager",
  ],
  minBasePay: ["0", "10", "20", "30", "40", "50", "60", "70"],
};
